title: Boon Chuan Tan # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software test engineer with experience in horizontal end-to-end testing of firmware and web applications for HP. Mastered the skill of documenting bugs and steps to replicate issues in JIRA and ZenTao through my employment as a software test engineer. Proficient in writing, debugging and executing automated test scripts using Python on Linux. 
  <br><br>
  <a href="https://www.linkedin.com/in/nitrolego/">View My LinkedIn Profile</a>  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: 368761539 # your Google Analytics tracking ID here
